// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ContactMeButtonComponent: typeof import('./components/ContactMeButtonComponent.vue')['default']
    ExperiencesComponent: typeof import('./components/ExperiencesComponent.vue')['default']
    ExpertiseComponent: typeof import('./components/ExpertiseComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    PageTransition: typeof import('./components/PageTransition.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
